### ISSUE TITLE
Training results not as good as the ones shown in the paper

### ISSUE THREAD

**Issue by CiciBEASTARS** [tijiang13/InstantAvatar#12]
Thanks for your fantastic work!!!

I'm a little confused about the reconstruction results. When I try to train "male-4-casual" in people snapshot dataset, I got this blurred result. I trained it with the default config (confs/dataset/peoplesnapshot/male-4-casual.yaml) and ran the command in bash/run_peoplesnapshot.sh on a RTX3090. I've tried training with more epochs but couldn't see any improvement.
![27](https://github.com/tijiang13/InstantAvatar/assets/97783743/2a42ebd6-eab1-4c46-8a5d-1263c5d4a49b)

I've tried other videos, some give high-quality results as shown in the paper, but others suffer from this floating artifact, and I can't find the reason for this.

Do you have any idea of what's happening here? Looking forward to the reply!

**Comment by tijiang13** [comment]
Hi,

I just tried the "bash/run_peoplesnapshot.sh" on my machine, and here is what it gives after 30 epochs:

![image](https://github.com/tijiang13/InstantAvatar/assets/15152165/466e6075-f244-407a-bcb1-130fc22bd4a9)

Usually the floating noise stems from the inaccurate pose estimation and on-the-fly pose refinement is required as is illustrated in the in-the-wild demo. But in the `bash/run_peoplesnapshot.sh` example we didn't refine the poses because we have provided refined poses in the `data/` folder.

I'd recommend checking if there is some code modified accidently with `git status`, or to a clean clone to see if the problem persists.

Best,
Tianjian

**Comment by CiciBEASTARS** [comment]
Thanks for your quick response!

I just discovered that there is no optimized pose for `male-4-casual` in the `data/` folder. I will follow the pose refinement process and try again.

Thanks again!

**Comment by tijiang13** [comment]
> Thanks for your quick response!
> 
> I just discovered that there is no optimized pose for `male-4-casual` in the `data/` folder. I will follow the pose refinement process and try again.
> 
> Thanks again!

Hi,

I somehow forgot to upload the refined poses for that sequence... Now it's uploaded and you can give it a quick check.

Thanks for the good catch!

Best,
Tianjian
