### ISSUE TITLE
Question about training own videos

### ISSUE THREAD

**Issue by 1211186431** [tijiang13/InstantAvatar#19]
Hello, I have successfully reproduced the results of the paper on both people-snapshot and Neuman datasets, and indeed the performance is quite good!
There are several issues I encountered while training my own video, and I hope to get some answers.
1.In `./bash/run-neuman-demo.sh`, `fit.py `and `train.py` were run in sequence. I want to understand the connection and differences between these two.
2.How did you solve the problem of hand rendering? The results I generated have poor hand effects. Is it because of the lighting in the input video?

This is the output result.
![rotation](https://github.com/tijiang13/InstantAvatar/assets/56494120/45443e9f-ce1d-4868-bd2a-e4920c0ba589)

**Comment by tijiang13** [comment]
Here are some clarifications and insights regarding your points:

The main difference lies in whether the SMPL parameters are optimized or not. We adopted this two-stage strategy because, in some cases, it has shown slightly better reconstruction results.
I recently investigated the issue you mentioned, and I believe there are two underlying problems:
a) We didn't model the hand gesture explicitly, so if there are changes in the gesture during training, it can result in a blurry reconstruction of that specific part.
b) Currently, there is an issue within the preprocessing pipeline. Sometimes, after applying the [SMPL refinement script](https://github.com/tijiang13/InstantAvatar/blob/master/scripts/custom/refine-smpl.py), we observe severe jittering especially for the hands and head /  occluded body parts. I think this could be fixed by enforcing a temporal consistent loss during the preprocessing but I am still trying to find some time to test it.

Best,
Tianjian

**Comment by tijiang13** [comment]
@1211186431 

Just some quick updates:

1. I updated the preprocessing pipeline, now the reconstruction should have better hand quality.
2. Also, regarding the floating error, I think you might be able to get better result by setting the downscale to 2 in the configuration file.

Best,
Tianjian

**Comment by 1211186431** [comment]
Thank you for your reply, I will try immediately.
