### ISSUE TITLE
Question about the fit.py

### ISSUE THREAD

**Issue by Net-Maker** [tijiang13/InstantAvatar#53]
Thanks for your great work. I had read your paper for several times, as same as the Fast-SNARF.
But honestly, I cannot understand the usage of the "fit.py". 
It seems like you are training an articulation space's avatar, or it's the process to train the Occupancy Network?
I think I haven't understood the paper, there must be some mistakes in my thought.
What's the difference between the fit/checkpoints and the output/checkpoints.
Sometimes the fit result is even better!
fit result : 
![049299](https://github.com/tijiang13/InstantAvatar/assets/79513614/a01e50c6-0e7d-4908-a0b6-1f6e3b7f63f7)
final result :
![029579](https://github.com/tijiang13/InstantAvatar/assets/79513614/3f5d3b6c-2ba6-4d53-819f-b4798b632452)

**Comment by tijiang13** [comment]
Hi,

During fitting phase, we leverage SMPL mesh to mitigate floating noise in order to stabilize SMPL fitting (refer to [this](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/deformers/smpl_deformer.py#L98)). While this approach is generally effective, it can negatively impact the performance of skirts. Therefore, we disable this functionality during the reconstruction phase (refer to [this](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/deformers/snarf_deformer.py#L119)).

Regarding the results you show above, I think it could be that the segmentation is somewhat problematic. You can check the generated mask in the data folder. Alternatively, you can try to increase the samples outside the body (change the configure in the [yaml file](https://github.com/tijiang13/InstantAvatar/blob/master/confs/sampler/patch.yaml#L4) or [here](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/utils/sampler.py#L52)).

Best, Tianjian

**Comment by Net-Maker** [comment]
Thanks for your really rapid and helpful answer !!!
