### ISSUE TITLE
Error on neuman's dataset

### ISSUE THREAD

**Issue by vrahnos3** [tijiang13/InstantAvatar#54]
Hello, thanks for the great work,
I followed the steps from readme to run neauman's - custom dataset. There was an error as you can see.
![Screenshot_1](https://github.com/tijiang13/InstantAvatar/assets/63507675/94f22659-9c15-414b-8650-c5e5f6c94e97)

I realised that on third_parties there isn't installed openpose. On readme you just mention that you use openpose but as I understood is a preliminary to install it on third_parties folder.

**Comment by tijiang13** [comment]
Hi Panos,

The "third_parties" directory includes code snippets borrowed from other projects, such as PyTorch3D. This is due to our utilization of only select functions from their codebase, and the original packages can pose installation challenges. Conversely, dependencies like ROMP, SAM, and OpenPose must be installed separately.

Sorry for any confusion caused by the naming.

Best, Tianjian

**Comment by vrahnos3** [comment]
@tijiang13 thanks for your quick reply, 
I just mention it for someone who has the same problem with me, because it took me some time to realise how the workflow is going.
