### ISSUE TITLE
export to fbx ?

### ISSUE THREAD

**Issue by nadavperez** [tijiang13/InstantAvatar#66]
how can i export the fbx ?

**Comment by tijiang13** [comment]
Hi nadavperez,

As we rely on a volume-base representation rather than a surface-based representation I think it's not very straightforward to convert it to format like fbx. But if you want to try you can try to run march-cubes algorithm and you will be able to get the data in obj format which can be then converted into fbx.

Best, Tianjian

Best, Tianjian

**Comment by nadavperez** [comment]
Thank you so much for the prompt reply.
Have you seen the FBX export for VIBE ?
https://github.com/mkocabas/VIBE
I am wondering if I could use a similar method to extract a rigged textured FBX

**Comment by tijiang13** [comment]
Hi nadavperez,

I checked the script. It looks that it uses blender to convert the meshes to fbx format.

And regarding your question, yes, if you have exported the animated meshes sequence already then you should be able to convert it in a similar fashion.

Best, Tianjian

**Comment by tijiang13** [comment]
But as noted above, that when converting volume-based avatars to mesh format, the quality of the mesh may degrade as the conversion process is not lossless. Please check this [issue](https://github.com/tijiang13/InstantAvatar/issues/39) on how to extract and what the result will look like before you give it a try.

Best, Tianjian
