### ISSUE TITLE
How to generate the noval pose file by my own video?

### ISSUE THREAD

**Issue by callmeyellowbin** [tijiang13/InstantAvatar#68]
Hi, thank you for your great job!

I have a problem about driving the reconstructed model by my own video. There is a file named 'aist_demo.npz' and I would like to generate my own npz file by my own video, could you please provide a way to generate it? Thank you a lot!

**Comment by tijiang13** [comment]
Hi Hoben,

Sorry for the delayed response as I've just returned from traveling. Regarding the poses, we stored them using NumPy, and that's why they are in the .npz format. In essence, it's only a Python dictionary, and once you have a similar dictionary like below, you can create a motion file using `numpy.savez(filename, **dict)`

```Python
{
  "betas": (1, 10),   # shape parameters
  "poses": (N, 72),   # pose parameters
  "trans": (N, 3),    # translation
}
```

You can refer to [L48-L49](https://github.com/tijiang13/InstantAvatar/blob/master/animate.py#L48-L49) for how we load and use the pose data. 

Best, Tianjian

**Comment by callmeyellowbin** [comment]
您的来信我已收到，祝好！
